In [11]:
import pandas as pd

df = pd.read_csv("Tweets.csv")  
df = df[["airline_sentiment", "text"]]
df.head()

  airline_sentiment                                               text
0           neutral                @VirginAmerica What @dhepburn said.
1          positive  @VirginAmerica plus you've added commercials t...
2           neutral  @VirginAmerica I didn't today... Must mean I n...
3          negative  @VirginAmerica it's really aggressive to blast...
4          negative  @VirginAmerica and it's a really big bad thing...

In [12]:
%pip install nltk

Requirement already satisfied: nltk in c:\users\nexen technologies\appdata\local\programs\python\python312\lib\site-packages (3.10.3)
Requirement already satisfied: defusedxml in c:\users\nexen technologies\appdata\local\programs\python\python312\lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in c:\users\nexen technologies\appdata\local\programs\python\python312\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\nexen technologies\appdata\local\programs\python\python312\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\nexen technologies\appdata\local\programs\python\python312\lib\site-packages (from nltk) (2026.9.29)
Requirement already satisfied: tqdm in c:\users\nexen technologies\appdata\local\programs\python\python312\lib\site-packages (from nltk) (4.70.1)
Requirement already satisfied: colorama in c:\users\nexen technologies\appdata\local\programs\python\python312\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
import nltk
import string
import re
from nltk.stem.porter import PorterStemmer

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')
from nltk.corpus import stopwords

ps = PorterStemmer()
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'http.?://[^\s]+[\s]?', '', text)
    text = nltk.word_tokenize(text)
    y = []
    for i in text:
        if i not in stop_words:
            y.append(i)
    text = y[:]
    y.clear()
    for i in text:
        y.append(ps.stem(i))
    return " ".join(y)

df["text_cleaned"] = df["text"].apply(clean_text)
df.head()

[nltk_data] Downloading package stopwords to C:\Users\NEXEN
[nltk_data]     TECHNOLOGIES\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to C:\Users\NEXEN
[nltk_data]     TECHNOLOGIES\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\NEXEN
[nltk_data]     TECHNOLOGIES\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

,airline_sentiment,text,text_cleaned
0,neutral,@VirginAmerica What @dhepburn said.,@ virginamerica @ dhepburn said .
1,positive,@VirginAmerica plus you've added commercials t...,@ virginamerica plu 've ad commerci experi ......
2,neutral,@VirginAmerica I didn't today... Must mean I n...,@ virginamerica n't today ... must mean need t...
3,negative,@VirginAmerica it's really aggressive to blast...,@ virginamerica 's realli aggress blast obnoxi...
4,negative,@VirginAmerica and it's a really big bad thing...,@ virginamerica 's realli big bad thing

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=3000)
X = tfidf.fit_transform(df["text_cleaned"]).toarray()
Y = df["airline_sentiment"].values

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=2
)

# Multinomial Naive Bayes
nb = MultinomialNB()
nb.fit(X_train, y_train)
y_pred_nb = nb.predict(X_test)
print("Naive Bayes accuracy:", accuracy_score(y_test, y_pred_nb))

# Random Forest
model = RandomForestClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Random Forest accuracy:", accuracy_score(y_test, y_pred))

Naive Bayes accuracy: 0.7219945355191257
Random Forest accuracy: 0.7496584699453552